## Упражнения по библиотеке Numpy

In [8]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [9]:
a = np.random.randint(1, 15, 15)
a

array([ 4,  8, 10,  3,  8,  8, 10,  9,  9,  5, 12,  2,  5,  5,  3])

In [10]:
a[(a>3) & (a<8)] = 0
a

array([ 0,  8, 10,  3,  8,  8, 10,  9,  9,  0, 12,  2,  0,  0,  3])

**2.** Заменить максимальный элемент случайного массива на 0

In [11]:
a = np.random.randint(1, 15, 15)
a

array([ 9,  9, 13,  5, 13,  3,  2,  1,  2,  9, 10,  4,  6,  5,  9])

In [12]:
a[a.argmax()] = 0
a

array([ 9,  9,  0,  5, 13,  3,  2,  1,  2,  9, 10,  4,  6,  5,  9])

**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [13]:
def func1(arr):    
    grids = np.meshgrid(*arr)
    flattened_grids = [grid.ravel() for grid in grids]
    result = np.column_stack(flattened_grids)
    return result

arr = np.array([[1, 2], [3, 4], [5, 6]])
result = func1(arr)
print(result)

[[1 3 5]
 [1 3 6]
 [2 3 5]
 [2 3 6]
 [1 4 5]
 [1 4 6]
 [2 4 5]
 [2 4 6]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [14]:
a = np.random.randint(1, 8, (8, 3))
b = np.random.randint(1, 8, (2, 2))

In [15]:
a

array([[3, 7, 6],
       [2, 6, 4],
       [4, 7, 5],
       [1, 4, 6],
       [1, 4, 7],
       [3, 5, 3],
       [5, 2, 2],
       [3, 5, 1]])

In [16]:
b

array([[4, 1],
       [7, 1]])

In [17]:
def func2(A, B):
    return A[np.intersect1d(np.any(np.isin(A, B[0]), axis=1).nonzero(), np.any(np.isin(A, B[1]), axis=1).nonzero())]
        

func2(a, b)

array([[4, 7, 5],
       [1, 4, 6],
       [1, 4, 7],
       [3, 5, 1]])

**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [18]:
a = np.random.randint(1, 4, (10, 3))
a

array([[1, 2, 3],
       [3, 2, 3],
       [3, 3, 2],
       [3, 2, 3],
       [3, 2, 2],
       [3, 2, 3],
       [1, 2, 3],
       [2, 3, 2],
       [3, 2, 2],
       [3, 2, 3]])

In [19]:
def func3(arr):
    a = np.diff(arr, axis=1)
    return arr[(a!=0).any(axis=1)]

func3(a)

array([[1, 2, 3],
       [3, 2, 3],
       [3, 3, 2],
       [3, 2, 3],
       [3, 2, 2],
       [3, 2, 3],
       [1, 2, 3],
       [2, 3, 2],
       [3, 2, 2],
       [3, 2, 3]])

**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [20]:
a = np.random.randint(1, 4, (20, 3))
a

array([[1, 1, 1],
       [3, 2, 1],
       [3, 3, 1],
       [3, 2, 2],
       [1, 3, 2],
       [1, 1, 3],
       [1, 2, 2],
       [3, 1, 2],
       [3, 1, 1],
       [1, 3, 2],
       [1, 3, 2],
       [1, 3, 1],
       [2, 1, 3],
       [1, 3, 3],
       [2, 3, 3],
       [2, 2, 3],
       [3, 3, 1],
       [1, 2, 3],
       [2, 3, 3],
       [2, 3, 1]])

In [21]:
def func4(arr):
    return np.unique(a, axis = 0)

func4(a)

array([[1, 1, 1],
       [1, 1, 3],
       [1, 2, 2],
       [1, 2, 3],
       [1, 3, 1],
       [1, 3, 2],
       [1, 3, 3],
       [2, 1, 3],
       [2, 2, 3],
       [2, 3, 1],
       [2, 3, 3],
       [3, 1, 1],
       [3, 1, 2],
       [3, 2, 1],
       [3, 2, 2],
       [3, 3, 1]])

______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [22]:
a = np.random.randint(0, 3, (6,5))
a

array([[2, 0, 1, 2, 2],
       [1, 1, 1, 1, 2],
       [1, 2, 2, 2, 2],
       [2, 0, 2, 0, 2],
       [1, 0, 0, 2, 0],
       [1, 0, 1, 2, 1]])

In [23]:
def np_solution(arr):
    return np.prod(np.diag(arr)[np.diag(arr).nonzero()])

np_solution(a)

4

In [24]:
def py_solution(lst):
    diag_size = min(len(lst), len(lst[0]))
    res = 1
    for i in range(diag_size):
        res *= lst[i][i] if lst[i][i] else 1
    return res

py_solution([[0, 2, 0, 2, 2],
       [0, 0, 2, 1, 2],
       [0, 2, 1, 1, 0],
       [2, 0, 2, 2, 1],
       [1, 2, 1, 2, 2],
       [0, 1, 0, 1, 1]])

4

* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [25]:
x = np.array([1,2,2,4])
y = np.array([4,2,1,2])

In [26]:
def np_solution(x, y):
    return np.array_equal(np.sort(x), np.sort(y))
    
np_solution(x, y)

True

In [27]:
def py_solution(x, y):
    return sorted(x) == sorted(y)

py_solution([1, 2, 2, 4], [4, 2, 1, 2])

True

* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [28]:
a = np.random.randint(0, 8, 15)
a

array([0, 3, 1, 1, 3, 3, 6, 4, 6, 3, 1, 1, 0, 5, 5])

In [29]:
def np_solution(arr):
    a = arr[:-1]
    return np.max(arr[np.add((a==0).nonzero(), 1)])

np_solution(a)

5

In [30]:
def py_solution(lst):
    vals = []
    for i in range(len(lst)-1):
        if lst[i] == 0:
            vals.append(lst[i+1])
    return max(vals)

py_solution([6, 0, 6, 2, 5, 2, 2, 7, 4, 4, 2, 6, 0, 0, 0])

6

* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [19]:
a = np.random.randint(1, 4, 15)
a =  np.array([2, 2, 2, 5, 3, 3, 3])

In [40]:
def np_solution(arr):
    return np.unique(a, return_counts=True)
    
np_solution(a)

(array([2, 3, 5]), array([3, 3, 1], dtype=int64))

In [45]:
def py_solution(lst):
    num, count = [lst[0]], [1]
    for i in lst[1:]:
        if num[-1] == i:
            count[-1] +=1
        else:
            num.append(i)
            count.append(1)
    return num, count
        
py_solution([2, 2, 2, 3, 3, 3, 5, 3, 4, 4])

([2, 3, 5, 3, 4], [3, 3, 1, 1, 2])

* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [48]:
from scipy.spatial.distance import cdist

In [50]:
x = np.random.randint(1, 10, (7, 3)) # 7 обьектов по 3 измерения у каждого
y = np.random.randint(1, 10, (8, 3)) # 8 обьектов по 3 измерения у каждого
print(x, y, sep="\n\n")

[[1 8 3]
 [2 7 9]
 [7 8 8]
 [7 4 3]
 [3 1 9]
 [3 3 7]
 [8 1 5]]

[[7 3 1]
 [6 6 6]
 [2 9 1]
 [3 9 6]
 [9 1 8]
 [1 6 2]
 [5 4 1]
 [3 2 7]]


In [67]:
def np_solution(X, Y):
    a = X[np.newaxis, ...]
    b = Y[:, np.newaxis, :]
    return np.sum((a-b)**2, axis=-1)**0.5

np_solution(x, y)

array([[ 8.06225775, 10.24695077,  8.60232527,  2.23606798,  9.16515139,
         7.21110255,  4.58257569],
       [ 6.164414  ,  5.09901951,  3.        ,  3.74165739,  6.55743852,
         4.35889894,  5.47722558],
       [ 2.44948974,  8.24621125,  8.66025404,  7.34846923, 11.35781669,
         8.54400375, 10.77032961],
       [ 3.74165739,  3.74165739,  4.58257569,  7.07106781,  8.54400375,
         6.08276253,  9.48683298],
       [11.74734012,  9.2736185 ,  7.28010989,  6.164414  ,  6.08276253,
         6.40312424,  3.16227766],
       [ 2.23606798,  7.14142843,  8.71779789,  6.40312424,  8.83176087,
         6.164414  ,  9.11043358],
       [ 6.        ,  9.05538514,  8.30662386,  2.82842712,  8.77496439,
         6.40312424,  5.83095189],
       [ 7.48331477,  5.47722558,  7.28010989,  6.        ,  2.23606798,
         1.        ,  5.47722558]])

In [71]:
def py_solution(X, Y):
    res = [[] for i in range(len(Y))]
    for i in range(len(X)):
        for j in range(len(Y)):
            dist = 0
            for k in range(len(X[0])):
                dist+=(X[i][k]-Y[j][k])**2
            res[j].append(dist**0.5)
    return res

py_solution(x.tolist(), y.tolist())

[[8.06225774829855,
  10.246950765959598,
  8.602325267042627,
  2.23606797749979,
  9.16515138991168,
  7.211102550927978,
  4.58257569495584],
 [6.164414002968976,
  5.0990195135927845,
  3.0,
  3.7416573867739413,
  6.557438524302,
  4.358898943540674,
  5.477225575051661],
 [2.449489742783178,
  8.246211251235321,
  8.660254037844387,
  7.3484692283495345,
  11.357816691600547,
  8.54400374531753,
  10.770329614269007],
 [3.7416573867739413,
  3.7416573867739413,
  4.58257569495584,
  7.0710678118654755,
  8.54400374531753,
  6.082762530298219,
  9.486832980505138],
 [11.74734012447073,
  9.273618495495704,
  7.280109889280518,
  6.164414002968976,
  6.082762530298219,
  6.4031242374328485,
  3.1622776601683795],
 [2.23606797749979,
  7.14142842854285,
  8.717797887081348,
  6.4031242374328485,
  8.831760866327848,
  6.164414002968976,
  9.1104335791443],
 [6.0,
  9.055385138137417,
  8.306623862918075,
  2.8284271247461903,
  8.774964387392123,
  6.4031242374328485,
  5.8309518948

In [76]:
def scipy_solution(X, Y):
    return cdist(Y, X, metric="euclidean")

scipy_solution(x, y)

array([[ 8.06225775, 10.24695077,  8.60232527,  2.23606798,  9.16515139,
         7.21110255,  4.58257569],
       [ 6.164414  ,  5.09901951,  3.        ,  3.74165739,  6.55743852,
         4.35889894,  5.47722558],
       [ 2.44948974,  8.24621125,  8.66025404,  7.34846923, 11.35781669,
         8.54400375, 10.77032961],
       [ 3.74165739,  3.74165739,  4.58257569,  7.07106781,  8.54400375,
         6.08276253,  9.48683298],
       [11.74734012,  9.2736185 ,  7.28010989,  6.164414  ,  6.08276253,
         6.40312424,  3.16227766],
       [ 2.23606798,  7.14142843,  8.71779789,  6.40312424,  8.83176087,
         6.164414  ,  9.11043358],
       [ 6.        ,  9.05538514,  8.30662386,  2.82842712,  8.77496439,
         6.40312424,  5.83095189],
       [ 7.48331477,  5.47722558,  7.28010989,  6.        ,  2.23606798,
         1.        ,  5.47722558]])

In [77]:
%%timeit
np_solution(x, y)

17.5 µs ± 446 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [78]:
%%timeit
py_solution(x, y)

251 µs ± 9.92 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [80]:
%%timeit
scipy_solution(x, y)

6.93 µs ± 203 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [81]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [82]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [84]:
average_calories = np.average(calorie_stats)
average_calories

106.88311688311688

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [85]:
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [86]:
median_calories = np.median(calorie_stats)
median_calories

110.0

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [97]:
for i in range(100):
    p = np.percentile(calorie_stats, i)
    print(p)
    if p > 60:
        nth_percentile = i   
        break
nth_percentile

50.0
50.0
50.0
55.599999999999994
70.0


4

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [99]:
more_calories = np.sum(calorie_stats > 60) / len(calorie_stats)
more_calories

0.961038961038961

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [100]:
np.std(calorie_stats)

19.35718533390827

Меньшее стандартное отклонение говорит о том, что в целом разбег от некоторого среднего значения калорий у конкурентов небольшой. Учитывая то, что уровень уровень калорий нашего продукта меньший чем наиболее вероятное значение калорий потенциального конкурента, то можно сделать вывод, что наш продукт содержит меньше калорий чем абсолютное большинство конкуретнов.

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

Проведенный анализ сравнительный анализ калорий конкурентов с нашей продукцией позволяет обьективно оценить преимущества продукции нашей компании. Полуенные данные можно вывести в отдельный дашборд, который, в отличие от иноформации в текстовом виде, будет отображать понятнее потенциальному покупателю преимущества злаков CrunchieMunchies перед конкурентами.